language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
  - ".cache"
deploy:
  provider: heroku
  on: master
  api_key:
    secure: Q+LATcRIQP9EDZcunMglOwoYEjpPHTJ+AitufBSWIeC7gvaVRVHM/LAPLnAHkuhDv4C7c8Dsz5ttrYiu497O0WdvZLWR3moSrsxqPFyo25kvZ6mHmjY8lbUvSoZxYGFZzPaKOMwrh983+CYYkqsR7eMtIEPjmmPRYgAPkbQTOhyIWbAp4yJo36rSxgD62CIOaOGxqpNgG/ffQxp/0lA8f8kL2HFvwiO10rCMrhi6P4czTT5pmGsjXRGulSZNDaj0/S9M3RtWI3zBn+i5eqYFeNGRUUgzSqqMYvghtTP4J0Pifkx7XY7J9hoENDSe2a4upiwxywz+Qdf2+VE1Pv6eFEkNEArNFTt13BFiHojnZyltmOPlCFK5pE2xMbtgXSxdsKHRPKsPBKgj6GAoYchuxeTJDaFWj9rAAZtzs2O4s5pj6YRCxDOrubKJNHG3h4gRKKbFj02WyozhQUUGPwEzbUGGZoqlRBFQt201BYjJ/zRX1a0YsIj0v1/kssd2WvOoM1ukpVmJ2sDmWquiwjgjPTIZRHMpZ+coYiF+HP24EavUzSgT+3EFxZdEsu33U1Rxyk1eaOH24QZSHyYSOix1zm+xE6Jko5nGuv/4dDow0sOj8w9G/CE5W5neoW5w78ignnnXnhmi+QJgTdwPlaD82erdenMEniWD6Sh1LJ8xScg=
