language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_fceaa16ce1a1_key -iv $encrypted_fceaa16ce1a1_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
script:
- npm test
- npm start
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
