language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_b7ccb24178b3_key -iv $encrypted_b7ccb24178b3_iv
  -in deploy.key.enc -out deploy.key -d
