language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
  - ".cache"
deploy:
  provider: heroku
  on: master
  api_key:
    secure: Q+LATcRIQP9EDZcunMglOwoYEjpPHTJ+AitufBSWIeC7gvaVRVHM/LAPLnAHkuhDv4C7c8Dsz5ttrYiu497O0WdvZLWR3moSrsxqPFyo25kvZ6mHmjY8lbUvSoZxYGFZzPaKOMwrh983+CYYkqsR7eMtIEPjmmPRYgAPkbQTOhyIWbAp4yJo36rSxgD62CIOaOGxqpNgG/ffQxp/0lA8f8kL2HFvwiO10rCMrhi6P4czTT5pmGsjXRGulSZNDaj0/S9M3RtWI3zBn+i5eqYFeNGRUUgzSqqMYvghtTP4J0Pifkx7XY7J9hoENDSe2a4upiwxywz+Qdf2+VE1Pv6eFEkNEArNFTt13BFiHojnZyltmOPlCFK5pE2xMbtgXSxdsKHRPKsPBKgj6GAoYchuxeTJDaFWj9rAAZtzs2O4s5pj6YRCxDOrubKJNHG3h4gRKKbFj02WyozhQUUGPwEzbUGGZoqlRBFQt201BYjJ/zRX1a0YsIj0v1/kssd2WvOoM1ukpVmJ2sDmWquiwjgjPTIZRHMpZ+coYiF+HP24EavUzSgT+3EFxZdEsu33U1Rxyk1eaOH24QZSHyYSOix1zm+xE6Jko5nGuv/4dDow0sOj8w9G/CE5W5neoW5w78ignnnXnhmi+QJgTdwPlaD82erdenMEniWD6Sh1LJ8xScg=
  app: three-dog-bot
env:
  global:
    secure: PB8gKnNGrr5EIapCD/38wXuOYDG3Bjm26hW+RY+4CpV2Kh0oELBGQs1bw4RoByIVhgHxTuxO8Yk11l/spZTkqxbgf6vzEagn6GwLdFQ+7ZQksaK7tjwWKby2Ugdu2igPaO1iP2r6buX2mlEO8slFsnbBAwwVMhcukVeu95Tv5sZxjBTFeEb66+w0I6tJvlSxYOGaaPd9jmC1cXGKRFtVE9y/yYCvKO/D9v1Lk7GjPxttBoj0Ik7UAISr1fXzxSk7S6TcBj6/AzPUOhX63Sn3dRlEN1imcPynFjBpR79uiuTe7HV/DV5vxZeOP0VETMTceXOA6JgYIMmxboANC5fhoN61CZe0IQGNyrF+rmSZHgfnUOn8VFCy2TOSqsj+mM0+1Jn+ORzwaX0djjVxYtnIzWhnODcXP/r3wavyyKd1ebuL1TYBPLn8FhddA1RQu7uz5O2NrWmpjqwzZ2/jXAezPYQsAnM5CcmQD1FuQzu93ozmDqM2y4+TPthnZXurGqygVWRofGyaX+/A2UECz7osv5aatGjqAkDECM/MRxKunGVxX7R9OJXKurgo+PF/Xr8aGjcHpVVVXOBYBkxdoVZWCmpAuaC/9LUiVgQpP6hAwLKJxVvN0Qcgugs3HvjkncCJdv99xv4mrjBNpPO1/B7uJTKCuhzrP+RE9yljOMDjfrE=
