name: Docker Image CI

on:
  push:
    branches: [ $default_branch ]
  pull_request:
    branches: [ $default_branch ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/Pragma8123/three-dog:$(date +%s)
    
    - name: Push Docker image to Github registry
      run: docker push ghcr.io/Pragma8123/three-dog:$(date +%s)
